=== Eric-Brison/dynacase-extui/Action/Extui/menu.dtd
<!ELEMENT menu ((itemmenu|itemlistmenu)+)>
<!ELEMENT itemlistmenu (label?,icon?,itemmenu+)>
<!ELEMENT itemmenu (label?,icon?,control*,script?,confirm?,url?)>
<!ELEMENT label (#PCDATA)>
<!ELEMENT icon EMPTY>
<!ELEMENT control EMPTY>
<!ELEMENT script EMPTY>
<!ELEMENT url EMPTY>
<!ELEMENT confirm (label,continue?,cancel?)>
<!ELEMENT continue (#PCDATA)>
<!ELEMENT cancel (#PCDATA)>


<!ATTLIST itemlistmenu id CDATA #REQUIRED>
<!ATTLIST itemmenu id CDATA #REQUIRED>
<!ATTLIST itemmenu target CDATA #IMPLIED>
<!ATTLIST itemmenu type (menu|separator|text) "menu">
<!ATTLIST itemmenu useselection  (yes|no) "no">
<!ATTLIST icon src CDATA #REQUIRED>
<!ATTLIST url href CDATA #IMPLIED>
<!ATTLIST url method CDATA #IMPLIED>
<!ATTLIST script file CDATA #REQUIRED>
<!ATTLIST script class CDATA #REQUIRED>
<!ATTLIST control privilege CDATA #IMPLIED>
<!ATTLIST control method CDATA #IMPLIED>
<!ATTLIST control object CDATA #IMPLIED>
<!ATTLIST control visibility (hidden|visible|disabled) #REQUIRED>
<!ATTLIST itemmenu visibility (hidden|visible|disabled) "visible">
<!ATTLIST menu id CDATA #REQUIRED>

=== Eric-Brison/dynacase-extui/Action/Extui/default-context-menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE menu SYSTEM "menu.dtd">
<menu id="context">
	<itemlistmenu id="docctx">
		<label>[TITLE]</label>
		<icon src="[ICON]"></icon>
		<itemmenu id="title" type="text" target="_document">
			<label>[TITLE]</label>
			<icon src="[ICON]"/>
		</itemmenu>
		<itemmenu id="sep1" type="separator"/>
		<itemmenu id="view" target="_document">
			<label>[TEXT:eui:View Document]</label>
			<script file="lib/ui/fdl-interface-action-common.js" class="Fdl.InterfaceAction.ViewDocument"/>
		</itemmenu>
		<itemmenu id="edit" target="_document" visibility="hidden">
			<label>[TEXT:eui:Edit document]</label>
			<control method="!canEdit()" visibility="visible"/>
			<script file="lib/ui/fdl-interface-action-common.js" class="Fdl.InterfaceAction.EditDocument"/>
		</itemmenu>
		<itemmenu id="delete" target="_self" visibility="hidden" useselection="yes">			
			<label>[TEXT:eui:Delete]</label>
			<control privilege="delete" visibility="visible"/>
			<script file="lib/ui/fdl-interface-action-common.js" class="Fdl.InterfaceAction.Delete"/>
			<confirm>
				<label>[TEXT:eui:Sure delete ?]</label>
				<continue>[TEXT:eui:Delete]</continue> 
				<cancel>[TEXT:eui:Cancel deletion]</cancel> 
			</confirm>
		</itemmenu>   
		<itemmenu id="remove" target="_self" visibility="hidden" useselection="yes">
			<label>[TEXT:eui:Remove from folder]</label>
			<control object="folder" privilege="modify" visibility="visible"/>
			<script file="lib/ui/fdl-interface-action-common.js" class="Fdl.InterfaceAction.RemoveFromFolder"/>
			<confirm>
				<label>[TEXT:eui:Sure remove from folder ?]</label>
				<continue>[TEXT:eui:Remove from folder]</continue> 
				<cancel>[TEXT:eui:Cancel remove]</cancel> 
			</confirm>
		</itemmenu>     
		<itemmenu id="copy" target="_self" visibility="hidden">
			<label>[TEXT:eui:Duplicate document]</label>
			<control object="folder" privilege="modify" visibility="visible"/>
			<script file="lib/ui/fdl-interface-action-common.js" class="Fdl.InterfaceAction.Duplicate"/>
		</itemmenu>    
		<itemmenu id="lock" target="_self" visibility="hidden" useselection="yes">
			<label>[TEXT:eui:Lock]</label>
			<control method="canLock()" visibility="visible"/>
			<control method="isLocked()" visibility="hidden"/>
			<!--<icon src="lock.png"/>-->
			<script file="lib/ui/fdl-interface-action-common.js" class="Fdl.InterfaceAction.Lock"/>
		</itemmenu>  
		<itemmenu id="unlock" target="_self" useselection="yes">
			<label>[TEXT:eui:Unlock]</label>
			<control method="!isLocked()" visibility="hidden"/>
			<control method="!canUnLock()" visibility="hidden"/>
			<script file="lib/ui/fdl-interface-action-common.js" class="Fdl.InterfaceAction.Unlock"/>
		</itemmenu>
		<itemmenu id="mail" target="_self" visibility="hidden">
			<label>[TEXT:eui:Send Mail]</label>
			<control privilege="send" visibility="visible"/>
			<!--<script file="lib/ui/fdl-interface-action-common.js" class="Fdl.InterfaceAction.SendMail"/>-->
			<url href="?app=FDL&amp;action=EDITMAIL&amp;mid=%ID%&amp;viewdoc=N"/>
		</itemmenu>
		<itemmenu id="printview" target="_hidden" visibility="visible">
			<label>[TEXT:eui:View print version]</label>
			
			<!--<script file="lib/ui/fdl-interface-action-common.js" class="Fdl.InterfaceAction.SendMail"/>-->
			<url  href="javascript:window.open('?app=FDL&amp;action=IMPCARD&amp;view=print&amp;id=%ID%','_blank')" />
		</itemmenu>
		<itemmenu id="rsslink" target="_self" visibility="hidden">
			<label>[TEXT:eui:Rss Link]</label>
			<control method="equal('defDoctype','D')" visibility="visible"/>
			<!--<url href="?app=FREEDOM&amp;action=FREEDOM_RSS&amp;authtype=open&amp;id=%ID%"/>-->
			<url method="::getRssLink()"/>
		</itemmenu>
		<itemmenu id="sep2" type="separator"/>
		<itemmenu id="histo" target="_history">
			<label>[TEXT:eui:Historic]</label>
			<script file="lib/ui/fdl-interface-action-common.js" class="Fdl.InterfaceAction.Historic"/>
		</itemmenu>
		
                <itemmenu id="properties">
                        <label>[TEXT:eui:View Properties]</label>
                        <url href="?app=FDL&amp;action=IMPCARD&amp;zone=FDL:VIEWPROPERTIES:T&amp;id=%ID%"/>
                </itemmenu>
	</itemlistmenu>
	
</menu>

=== Eric-Brison/dynacase-extui/Action/Extui/default-collection-menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE menu SYSTEM "menu.dtd">
<menu id="DIR">
	<itemmenu id="createsearch" target="_self" visibility="hidden">
        <label>[TEXT:eui:Create a search]</label>
        <control method="equal(doctype,'T')" visibility="visible"/>
        <control method="!equal(defDoctype,'S')" visibility="hidden"/>
		<script file="lib/ui/fdl-interface-action-collection.js" class="Fdl.InterfaceAction.CreateSearch"/>
    </itemmenu>
	<itemlistmenu id="display">
        <label>[TEXT:eui:Display]</label>
        <itemmenu id="griddisplay" target="_self">
            <label>[TEXT:eui:Grid display]</label>
			<script file="lib/ui/fdl-interface-action-collection.js" class="Fdl.InterfaceAction.GridDisplay"/>
        </itemmenu>
		<itemmenu id="treedisplay" target="_self">
            <label>[TEXT:eui:Tree display]</label>
			<script file="lib/ui/fdl-interface-action-collection.js" class="Fdl.InterfaceAction.TreeDisplay"/>
        </itemmenu>
		<itemmenu id="icondisplay" target="_self">
            <label>[TEXT:eui:Icon display]</label>
			<script file="lib/ui/fdl-interface-action-collection.js" class="Fdl.InterfaceAction.IconDisplay"/>
        </itemmenu>
		<itemmenu id="abstractdisplay" target="_self">
            <label>[TEXT:eui:Abstract display]</label>
			<script file="lib/ui/fdl-interface-action-collection.js" class="Fdl.InterfaceAction.AbstractDisplay"/>
        </itemmenu>
    </itemlistmenu>
	<itemlistmenu id="selection">
		<label>[TEXT:eui:Selection]</label>
		<itemmenu id="lock" target="_self" useselection="yes">
			<label>[TEXT:eui:Lock selected documents]</label>
			<icon src="lib/ui/icon/lock.png"/>
			<script file="lib/ui/fdl-interface-action-common.js" class="Fdl.InterfaceAction.Lock"/>
			<confirm>
				<label>[TEXT:eui:Sure lock selected document ?]</label>
				<continue>[TEXT:eui:Lock selection]</continue> 
				<cancel>[TEXT:eui:Cancel locking]</cancel> 
			</confirm>
		</itemmenu>
        <itemmenu id="exportsel" target="_hidden" useselection="yes">
            <label>[TEXT:eui:Export selected documents]</label>
            <script file="lib/ui/fdl-interface-action-collection.js" class="Fdl.InterfaceAction.ExportSelection"/>
        </itemmenu>
	</itemlistmenu>
	<itemlistmenu id="tool">
        <label>[TEXT:eui:Tools]</label>
        <itemmenu id="export" target="_hidden">
            <label>[TEXT:eui:Export all documents]</label>
            <url href="?app=FDL&amp;action=EXPORTFLD&amp;id=%ID%&amp;wfile=Y&amp;code=utf8"/>
        </itemmenu>
    </itemlistmenu>
</menu>

=== Eric-Brison/dynacase-extui/Action/Extui/default-selection-context-menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE menu SYSTEM "menu.dtd">
<menu id="context">
	<itemlistmenu id="docctx">
		<!--<label>[TEXT:eui:Document Selection]</label>-->
		<itemmenu id="delete" target="_self">
			<label>[TEXT:eui:Delete]</label>
			<script file="lib/ui/fdl-interface-action-common.js" class="Fdl.InterfaceAction.Delete"/>
			<confirm>
				<label>[TEXT:eui:Sure delete ?]</label>
				<continue>[TEXT:eui:Delete]</continue> 
				<cancel>[TEXT:eui:Cancel deletion]</cancel> 
			</confirm>
		</itemmenu>   
		<itemmenu id="remove" target="_self" visibility="hidden">
                        <label>[TEXT:eui:Remove from folder]</label>
			<control object="folder" privilege="modify" visibility="visible"/>
			<script file="lib/ui/fdl-interface-action-common.js" class="Fdl.InterfaceAction.RemoveFromFolder"/>
			<confirm>
				<label>[TEXT:eui:Sure remove from folder ?]</label>
				<continue>[TEXT:eui:Remove from folder]</continue> 
				<cancel>[TEXT:eui:Cancel remove]</cancel> 
			</confirm>
		</itemmenu>
		<itemmenu id="lock" target="_self">
			<label>[TEXT:eui:Lock]</label>
			<!--<icon src="lock.png"/>-->
			<script file="lib/ui/fdl-interface-action-common.js" class="Fdl.InterfaceAction.Lock"/>
		</itemmenu>  
		<itemmenu id="unlock" target="_self">
			<label>[TEXT:eui:Unlock]</label>
			<script file="lib/ui/fdl-interface-action-common.js" class="Fdl.InterfaceAction.Unlock"/>
		</itemmenu>		
	</itemlistmenu>
</menu>
